name: stylelint
on: [push]
jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install --save-dev stylelint stylelint-config-standard
      - name: Create File
        uses: finnp/create-file-action@1.0.0
        env:
        FILE_NAME: '.stylelintrc.json'
        FILE_DATA: '{"extends": "stylelint-config-standard"}'
      - run: npx stylelint "**/*.css"
